export const FETCH_ALL_BANKS = "FETCH_ALL_BANKS";

export const FETCH_ALL_BANKS_SUCCESS = "FETCH_ALL_BANKS_SUCCESS";

export const FETCH_ALL_BANKS_FAILURE = "FETCH_ALL_BANKS_FAILURE";

export const FETCHING_DATA = "FETCHING_DATA";

export const UPDATE_SHOW_SIZE = "UPDATE_SHOW_SIZE";

export const UPDATE_PAGE = "UPDATE_PAGE";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";

export const CHANGE_CITY = "CHANGE_CITY";

export const SEARCH_BANKS = "SEARCH_BANKS";
