export const FETCH_ALL_BANKS = "FETCH_ALL_BANKS";

export const FETCH_ALL_BANKS_SUCCESS = "FETCH_ALL_BANKS_SUCCESS";

export const FETCH_ALL_BANKS_FAILURE = "FETCH_ALL_BANKS_FAILURE";

export const FETCHING_DATA = "FETCHING_DATA";
